CREATE TABLE ENDERECOS(
	ID_ENDERECO VARCHAR(255),
	ID_PESSOA VARCHAR(255),
	CEP VARCHAR(10),
	LOGRADOURO VARCHAR(255),
	NUMERO VARCHAR(50),
	COMPLEMENTO VARCHAR(50),
	BAIRRO VARCHAR(255),
	CIDADE VARCHAR(255),
	UF VARCHAR(2),
	IBGE INT,
	GIA INT,
	SIAFI INT,
	DDD INT,
	PRIMARY KEY (ID_ENDERECO)
);
ALTER TABLE ENDERECOS ADD CONSTRAINT FK_PESSOAS FOREIGN KEY (ID_PESSOA) REFERENCES PESSOAS (ID_PESSOA) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;