CREATE TABLE PESSOAS(
    ID_PESSOA VARCHAR(255) PRIMARY KEY,
	CPF_CNPJ VARCHAR(18) NOT NULL,
	ACESSOSISTEMA CHAR(1) NOT NULL CHECK (ACESSOSISTEMA IN ('S', 'N')),
	CLASSIFICACAO CHAR(1) NOT NULL,
	DATA_NASCIMENTO_FUNDACAO DATE CHECK (DATA_NASCIMENTO_FUNDACAO > '1900-01-01'),
	DATA_CADASTRO DATE CHECK (DATA_CADASTRO > DATA_NASCIMENTO_FUNDACAO),
	FANTASIA_FAZENDA VARCHAR(255),	
	INSCRICAO_ESTADUAL VARCHAR(255),
	INSCRICAO_MUNICIPAL VARCHAR(255),
	LOGIN VARCHAR(100),
	NOME_RAZAO_SOCIAL VARCHAR(255) NOT NULL,
	ORGAOEMISSOR VARCHAR(100),
	RG VARCHAR(100),
	SENHA VARCHAR(50),
	TIPO CHAR(1) NOT NULL,
	CHECK (TIPO IN ('F', 'J')),
	CHECK (CLASSIFICACAO IN ('A', 'C', 'F', 'P', 'O', 'S', 'F'))
);
INSERT INTO pessoas (id_pessoa, cpf_cnpj, acessosistema, classificacao, data_nascimento_fundacao,
				data_cadastro, fantasia_fazenda, login, nome_razao_social, senha, tipo)
			VALUES ('1', '123.456.789-00', 'S', 'A', '2010-01-01', '2022-09-01', 'USER MASTER', 
					'ADM', 'USER MASTER', '123456', 'F');